version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: dataops_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dataops
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: dataops_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: dataops_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backups:/app/backups
      - ./cloud_backups:/app/cloud_backups
    depends_on:
      - postgres
      - redis
      

   